import type { Config } from 'tailwindcss';

export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primaryBg: '#FFFFFF',
        secondaryBg: '#F9FAFB',
        figmaBg: '#f5f5f5',
        quaternaryFg: '#667085',
        buttonPrimaryBg: '#7F56D9',
        buttonPrimaryHoverBg: '#724dc3',
        buttonPrimaryFocusRing: '#a588e4',
        buttonSecondaryBg: '#FFFFFF',
        buttonSecondaryFg: '#344054',
        buttonSecondaryBorder: '#D0D5DD',
        buttonSecondaryDisabledFg: '#cdd0d6',
        buttonSecondaryHoverBg: '#f3f4f6',
        buttonSecondaryRing: '#f3f4f6',
        buttonSecondaryColorFg: '#6941C6',
        buttonSecondaryColorBg: '#FFFFFF',
        buttonSecondaryColorHoverBg: '#eee3fd',
        buttonSecondaryColorRing: '#eee3fd',
        buttonSecondaryColorBorder: '#D6BBFB',
        buttonSecondaryColorDisabledBg: '#faf8fe',
        buttonSecondaryColorDisabledFg: '#eee3fd',
        buttonTertiaryFg: '#475467',
        iconButtonRing: '#D0D5DD',
        textPrimary: '#101828',
        textSecondary: '#344054',
        textTertiary: '#475467',
        textPlaceholder: '#667085',
        borderPrimary: '#D0D5DD',
        borderSecondary: '#EAECF0',
      },
    },
  },
  plugins: [],
} satisfies Config;
